### ISSUE TITLE
Windows maximazed don't have gaps

### ISSUE THREAD

**Issue by artfox3** [Hegemonia123/FlexGrid#2]
Hi thnx for this amazing tool i'm really loving it, but i have one issue / request. When a window is maximized it doesn't preserve the gaps set by the script, and when u use meta+UP two times the window takes the entire screen with gaps on sides as expected but it isn't maximized.
So is there a way to apply gaps on maximized windows plus to make meta+UP maximize the window instead of just tile it to take the entire screen.
This behavior tho have an interesting usecase, to use the maximize mode as a fullscreen mode, what i mean is to keep the current behavior as is ( or add an option to toggle it on and off ) and set the panel to doge maximized windows, this will make maximized windows take all screen with no gaps and no panel, but it doesn't really work cause the panel in this mode doesn't preserve space so the window stays below it, this can be fixed by adding more space to the top gap, so to add custom gaps for each screen edge which i think will be easier to implement by you.

Sorry for making u read all of this lol.

**Comment by Hegemonia123** [comment]
Hi! 

I tried to mess with Kwins maximized state earlier, but faced some issues, which made me give up. 
1.  Kwin makes maximized windows look different (smaller shadow and borders, if I remember correctly). This only becomes visible when you make maximized window smaller without unmaximizing it.
2. Also setting and unsetting maximized state with flexGrid didn't work because Kwin wants to set the position and size of the window when changing the maximized state.
3. etc.

Border specific gaps would be doable. However, I'd guess the result wouldn't be very nice, since those uneven gaps would also be applied to smaller windows. 

I'm not sure if I understood your use-case or goal, but you can also affect the gab next to the panel by replacing `KWin.MaximizeArea` with `KWin.FullScreenArea` in the `getGeometry` function of `main.js` file :slightly_smiling_face: .

**Comment by artfox3** [comment]
Thnx for the reply, as for the maximized state i understand it seems it's hard to implement and may break stuff more than it fixes. I did test the custom gaps and indeed it also affected other small windows which isn't ideal, ill try to see how to make it only affect the top, thnx for ur other suggestions ill look them up.
